namespace FancyText.Core;

/// <summary>
/// 内置样式的英文层：NameEn / NoteEn 按 ID 补丁进 <see cref="StyleCatalog"/> 的内置定义（见 ApplyEnglish）。
/// 定名依据 docs/01 调研报告的英文来源站（coolsymbol / lingojam 等）与 Unicode 正式区段名；
/// 显示名中的装饰字符与序号（❶–❹、𝐁、❤ 等）原样保留。
/// </summary>
internal static class StyleEnglish
{
    /// <summary>样式 ID → 英文显示名。必须覆盖全部内置 ID（tests 的「英文层覆盖」断言强制）。</summary>
    public static IReadOnlyDictionary<string, string> Names { get; } = new Dictionary<string, string>
    {
        // ===== 特效（组合附加符号） =====
        ["juhua-1"] = "Chrysanthemum ❶",
        ["juhua-2"] = "Chrysanthemum ❷ (Ants)",
        ["juhua-3"] = "Chrysanthemum ❸",
        ["juhua-4"] = "Chrysanthemum ❹",
        ["strikethrough"] = "Strikethrough",
        ["strikethrough-double"] = "Double Strikethrough",
        ["strikethrough-slash"] = "Slash Strikethrough",
        ["strikethrough-tilde"] = "Tilde Strikethrough",
        ["underline"] = "Underline",
        ["underline-double"] = "Double Underline",
        ["underline-wavy"] = "Wavy Underline",
        ["overline"] = "Overline",
        ["overline-double"] = "Double Overline",
        ["dot-above"] = "Dot Above",
        ["ring-above"] = "Ring Above",
        ["arrow-above"] = "Arrow Above",
        ["enclose-circle"] = "Enclosed Circle",
        ["enclose-square"] = "Enclosed Square",
        ["enclose-diamond"] = "Enclosed Diamond",
        ["enclose-forbidden"] = "Enclosed Prohibited Sign",
        ["enclose-triangle"] = "Enclosed Triangle",
        ["snowflake-above"] = "Snowflake",
        ["bird-1"] = "Bird ❶",
        ["bird-2"] = "Bird ❷",
        ["butterfly"] = "Butterfly",
        ["tail"] = "Tail",
        ["smoke"] = "Smoke",
        ["smoke-thai"] = "Smoke ❷",
        ["sprout"] = "Sprout",
        ["heart-javanese"] = "Heart",
        ["vine-1"] = "Vine ❶",
        ["vine-2"] = "Vine ❷",
        ["hairpin"] = "Hairpin",
        ["zalgo-mini"] = "Zalgo Mini",
        ["zalgo-normal"] = "Zalgo Normal",
        ["zalgo-max"] = "Zalgo Max",

        // ===== 英文/字母花体 =====
        ["bold"] = "Bold 𝐁",
        ["italic"] = "Italic 𝐼",
        ["bold-italic"] = "Bold Italic 𝑯",
        ["script"] = "Script ℋ",
        ["bold-script"] = "Bold Script 𝓗",
        ["fraktur"] = "Fraktur (Old English) ℌ",
        ["bold-fraktur"] = "Bold Fraktur 𝕳",
        ["double-struck"] = "Double-Struck ℍ",
        ["monospace"] = "Monospace 𝙷",
        ["sans"] = "Sans 𝖧",
        ["sans-bold"] = "Sans Bold 𝗛",
        ["sans-italic"] = "Sans Italic 𝘏",
        ["sans-bold-italic"] = "Sans Bold Italic 𝙃",
        ["circled"] = "Circled ⓗ",
        ["circled-negative"] = "Negative Circled 🅗",
        ["squared"] = "Squared 🄷",
        ["squared-negative"] = "Negative Squared 🅷",
        ["parenthesized"] = "Parenthesized ⒣",
        ["regional-indicator"] = "Regional Indicator 🇭",
        ["fullwidth"] = "Fullwidth Ｈ (Vaporwave)",
        ["small-caps"] = "Small Caps ʜ",
        ["superscript"] = "Superscript ᴴ",
        ["subscript"] = "Subscript ₕ",
        ["currency"] = "Currency ₲",
        ["symbols-mix"] = "Symbols ђєll๏",

        // ===== 装饰 =====
        ["wing-classic"] = "Classic Wings ꧁꧂",
        ["wing-fancy"] = "Fancy Wings ꧁༺༻꧂",
        ["wing-delicate"] = "Delicate Wings ꧁༺๑༻꧂",
        ["wing-crown"] = "Crown Wings ꧁♛꧂",
        ["wing-flower"] = "Flower Wings ꧁❀꧂",
        ["wing-mystic"] = "Mystic Wings ༺ཌༀད༻",
        ["wing-tibetan"] = "Ancient Wings ༺ཌༀཉི༃ༀད༻",
        ["wing-angel"] = "Small Wings ʚɞ",
        ["wing-cloud"] = "Cloud Border ☁",
        ["wing-bow"] = "Bow ୨୧",
        ["border-star"] = "Star Border ★彡彡★",
        ["border-aesthetic"] = "Aesthetic Border ˜”*°•.",
        ["border-cute"] = "Sparkle Border ✧･ﾟ:",
        ["border-brackets-jp"] = "Japanese Brackets 『』",
        ["spacing-aesthetic"] = "Spaced H e l l o",
        ["spacing-wide"] = "Wide Ｈ ｅ ｌ ｌ ｏ",

        // ===== 变换 =====
        ["upside-down"] = "Upside Down oʇʇǝ",
        ["mirror"] = "Mirror oꞁꞁɘ",
        ["reverse"] = "Reversed olleH",
        ["leet"] = "Leet H3LL0",
        ["strip-marks"] = "Strip Marks",

        // ===== 中文 =====
        ["martian"] = "Martian",

        // ===== 编码 =====
        ["base64"] = "Base64",
        ["rot13"] = "ROT13",
        ["morse"] = "Morse Code",

        // ===== 扩充：组合符预设 =====
        ["paren-marks"] = "Arc Brackets ͜͡",
        ["stripes"] = "Stripes ͟͞",
        ["lightning"] = "Lightning ͛",
        ["wave-head"] = "Angle Above ̚",
        ["x-above"] = "X Above ̽",
        ["dot-below"] = "Dot Below ̣",
        ["manipuri-underline"] = "Manipuri Underline ꯭",
        ["lace"] = "Lace ஊ",
        ["grass"] = "Grass ෴",
        ["smoke-arabic"] = "Smoke ❸",

        // ===== 扩充：装饰模板 =====
        ["wing-elegant"] = "Elegant Wings ꧁❦༺",
        ["wing-diamond"] = "Diamond Wings ꧁༺◇",
        ["wing-double"] = "Double Wings ꧁༺༒",
        ["wing-shimmer"] = "Shimmer Wings ꧁༺✦",
        ["wing-soft"] = "Soft Wings ꧁༺❁",
        ["wing-sanskrit"] = "Tibetan Knot ༺࿈",
        ["wing-tibetan-ornament"] = "Tibetan Ornament ༺ཌ༈",
        ["wing-charm"] = "Charm Border ༄༊",
        ["wing-heart"] = "Sweetheart Brackets ෆ",
        ["wing-bunny"] = "Bunny Decor ₍ᐢ",
        ["wing-moonlight"] = "Moonlight Decor ☾༺",
        ["wing-starmoon"] = "Star and Moon Decor ☾✦",
        ["wing-asterism"] = "Asterism Decor ⁂",
        ["wing-retro"] = "Retro Pattern ꧁༺༽༾ཊ",
        ["wing-dots"] = "Dot Border ｡o○",
        ["wing-nested"] = "Nested Brackets ༼༺",
        ["wing-triangle"] = "Triangle Wings ꧁༺△",
        ["wing-love"] = "Heart Border •°•❤",

        // ===== 扩充：数字变体 / 俄化 / 火星文还原 =====
        ["digits-circled-sans"] = "Circled Sans Digits ➀",
        ["digits-double-circled"] = "Double Circled Digits ⓵",
        ["cyrillic-lookalike"] = "Cyrillic Lookalike",
        ["martian-reverse"] = "Martian Reverse",

        // ===== 中文扩充：简繁 / 拼音 =====
        ["simplified-to-traditional"] = "Simplified → Traditional",
        ["traditional-to-simplified"] = "Traditional → Simplified",
        ["pinyin"] = "Pinyin (toned) nǐ hǎo",
        ["pinyin-abbr"] = "Pinyin Abbr nhm",

        // ===== 扩充：编码 / 变换 =====
        ["braille"] = "Braille",
        ["nato"] = "NATO Alphabet",
        ["a1z26"] = "A1Z26",
        ["binary"] = "Binary",
        ["hex"] = "Hexadecimal",
        ["uppercase"] = "Uppercase ABC",
        ["lowercase"] = "Lowercase abc",
        ["alternating-case"] = "Alternating Case aLt",
    };

    /// <summary>样式 ID → 英文机制说明。必须覆盖全部内置 ID。</summary>
    public static IReadOnlyDictionary<string, string> Notes { get; } = new Dictionary<string, string>
    {
        // ===== 特效（组合附加符号） =====
        ["juhua-1"] = "Appends U+0488 (combining Cyrillic hundred thousands sign, dotted circle) after each grapheme",
        ["juhua-2"] = "Appends U+0489 (combining Cyrillic millions sign, dotted circle) after each grapheme",
        ["juhua-3"] = "Appends U+A670 (combining Cyrillic ten millions sign, dotted circle) after each grapheme; U+A671 is the hundred-millions variant",
        ["juhua-4"] = "Appends U+A672 (combining Cyrillic thousand millions sign, dotted circle) after each grapheme",
        ["strikethrough"] = "U+0336 combining long stroke overlay appended after each grapheme",
        ["strikethrough-double"] = "U+0347 combining equals sign below, renders as a double strikethrough, appended after each grapheme",
        ["strikethrough-slash"] = "U+0337 combining short solidus overlay appended after each grapheme",
        ["strikethrough-tilde"] = "U+0334 combining tilde overlay appended after each grapheme",
        ["underline"] = "U+0332 combining low line appended after each grapheme",
        ["underline-double"] = "U+0333 combining double low line appended after each grapheme",
        ["underline-wavy"] = "U+0330 combining tilde below appended after each grapheme",
        ["overline"] = "U+0305 combining overline appended after each grapheme",
        ["overline-double"] = "U+033F combining double overline appended after each grapheme",
        ["dot-above"] = "U+0307 combining dot above appended after each grapheme",
        ["ring-above"] = "U+030A combining ring above appended after each grapheme",
        ["arrow-above"] = "U+20D7 combining right arrow above appended after each grapheme",
        ["enclose-circle"] = "U+20DD combining enclosing circle appended after each grapheme; works on any CJK character, rendering depends on the platform",
        ["enclose-square"] = "U+20DE combining enclosing square appended after each grapheme",
        ["enclose-diamond"] = "U+20DF combining enclosing diamond appended after each grapheme",
        ["enclose-forbidden"] = "U+20E0 combining enclosing circle backslash (prohibited sign) appended after each grapheme",
        ["enclose-triangle"] = "U+20E4 combining enclosing upward pointing triangle appended after each grapheme",
        ["snowflake-above"] = "U+20F0 combining asterisk above (snowflake) appended after each grapheme",
        ["bird-1"] = "Appends U+0F7C (Tibetan vowel sign O) after each grapheme; looks like a small bird perched on top",
        ["bird-2"] = "Appends U+0F7D (Tibetan vowel sign OO) after each grapheme",
        ["butterfly"] = "Appends U+0F72 + U+0F80 (Tibetan vowel signs I and reversed I); together they look like a butterfly",
        ["tail"] = "Appends U+0F18 (Tibetan astrological sign khyud pa) after each grapheme",
        ["smoke"] = "Appends U+0F82 (Tibetan sign nyi zla naa da) after each grapheme; looks like smoke rising",
        ["smoke-thai"] = "Appends Thai tone mark mai tho ้ (U+0E49) × 4, stacked like smoke",
        ["sprout"] = "Appends Thai maitaikhu ็ (U+0E47) + mai tho ้ (U+0E49); a small sprout grows on top of each grapheme",
        ["heart-javanese"] = "Appends Javanese consonant sign cakra ꦿ (U+A9BF) + Balinese adeg adeg ᭄ (U+1B44) after each grapheme",
        ["vine-1"] = "Vine head built from ζ + Thai U+0E31 + combining double inverted breve U+0361, with ✿ appended at the end",
        ["vine-2"] = "Appends Javanese ꦿ + Balinese ᭄ after each grapheme, with the Tibetan mark ༎ (U+0FD0) appended at the end",
        ["hairpin"] = "Appends U+0749 (Syriac music) after each grapheme; shaped like a hairpin",
        ["zalgo-mini"] = "Zalgo: randomly stacks combining diacritics (U+0300–036F pool) on each grapheme, light intensity",
        ["zalgo-normal"] = "Zalgo: randomly stacks combining diacritics on each grapheme, medium intensity",
        ["zalgo-max"] = "Zalgo: randomly stacks combining diacritics on each grapheme, max intensity (may break line height)",

        // ===== 英文/字母花体 =====
        ["bold"] = "Mathematical bold, U+1D400 / U+1D41A / U+1D7CE",
        ["italic"] = "Mathematical italic, U+1D434 / U+1D44E (no digits)",
        ["bold-italic"] = "Mathematical bold italic, U+1D468 / U+1D482",
        ["script"] = "Mathematical script, U+1D49C / U+1D4B6; hole characters live in Letterlike Symbols",
        ["bold-script"] = "Mathematical bold script (the most common \"fancy script\"), U+1D4D0 / U+1D4EA",
        ["fraktur"] = "Mathematical Fraktur / Old English, U+1D504 / U+1D51E",
        ["bold-fraktur"] = "Mathematical bold Fraktur (most sites' \"Old English\" is actually this), U+1D56C / U+1D586",
        ["double-struck"] = "Mathematical double-struck, U+1D538 / U+1D552 / U+1D7D8",
        ["monospace"] = "Mathematical monospace (typewriter style), U+1D670 / U+1D68A / U+1D7F6",
        ["sans"] = "Mathematical sans-serif, U+1D5A0 / U+1D5BA / U+1D7E2",
        ["sans-bold"] = "Mathematical sans-serif bold, U+1D5D4 / U+1D5EE / U+1D7EC",
        ["sans-italic"] = "Mathematical sans-serif italic, U+1D608 / U+1D622",
        ["sans-bold-italic"] = "Mathematical sans-serif bold italic, U+1D63C / U+1D656",
        ["circled"] = "Circled letters: uppercase U+24B6 / lowercase U+24D0 / digits ①–⑨",
        ["circled-negative"] = "Negative circled letters U+1F150–169, uppercase only (lowercase maps to the same glyph)",
        ["squared"] = "Squared Latin capital letters U+1F130–149, uppercase only",
        ["squared-negative"] = "Negative squared Latin capital letters U+1F170–189, uppercase only",
        ["parenthesized"] = "Parenthesized letters: uppercase U+1F110 / lowercase U+249C / digits ⑴–⑼",
        ["regional-indicator"] = "Regional Indicator symbols U+1F1E6–1F1FF; two adjacent letters may combine into a country flag on Discord etc. (any letter pair can form a flag, e.g. com → 🇨🇴)",
        ["fullwidth"] = "Halfwidth → fullwidth: ASCII shifted by +0xFEE0, space → U+3000",
        ["small-caps"] = "Small capitals (phonetic extensions block); Q/X have no dedicated form (fallback ǫ/x)",
        ["superscript"] = "Superscript letters/digits (U+2070 area + spacing modifier letters); lowercase q has no superscript form",
        ["subscript"] = "Subscript letters/digits (U+2080 area + U+2090 area); most consonants have no subscript form",
        ["currency"] = "Currency-symbol lookalike substitution (instafonts/coolsymbol table)",
        ["symbols-mix"] = "Mixed Thai/Hebrew/Greek/Cyrillic lookalikes (coolsymbol \"Symbols\" table)",

        // ===== 装饰 =====
        ["wing-classic"] = "Javanese rerenggan brackets ꧁ U+A9C1 / ꧂ U+A9C2",
        ["wing-fancy"] = "Javanese brackets + Tibetan ornamental brackets ༺ U+0F3A / ༻ U+0F3B",
        ["wing-delicate"] = "Decorated with the Thai digit ๑ (U+0E51)",
        ["wing-crown"] = "Crown ♛ variant; so-called \"domineering\" styles are wing templates with crown/gem accents",
        ["wing-flower"] = "Dingbats white florette ❀ (U+2740)",
        ["wing-mystic"] = "Combined Tibetan letters and signs (ཌ ༀ ད)",
        ["wing-tibetan"] = "Full Tibetan decoration set (ཉི ༃ are the sun-and-moon vowel marks)",
        ["wing-angel"] = "Armenian/Georgian lookalike characters",
        ["wing-cloud"] = "Miscellaneous Symbols cloud ☁ (U+2601)",
        ["wing-bow"] = "Oriya digit characters ୨୧ (U+0B68 / U+0B67)",
        ["border-star"] = "Dingbats star ★ plus katakana-derived bristle marks 彡",
        ["border-aesthetic"] = "Aesthetic flourish border (common lingojam/fancytextpro template)",
        ["border-cute"] = "Japanese-style sparkle border template",
        ["border-brackets-jp"] = "CJK punctuation white corner brackets 『』",
        ["spacing-aesthetic"] = "Inserts a space between graphemes (aesthetic spacing; works for CJK too: 你 好)",
        ["spacing-wide"] = "Fullwidth mapping + spaces (wide); only affects Latin letters/digits/halfwidth punctuation",

        // ===== 变换 =====
        ["upside-down"] = "Substitutes via the upside-down map (fileformat.info table), then reverses the whole string",
        ["mirror"] = "Substitutes via the mirror map, then reverses the whole string (smalltextgen table)",
        ["reverse"] = "Reverses the string by grapheme (surrogate pairs and combining marks stay intact)",
        ["leet"] = "Basic leetspeak: a→4 e→3 i→1 o→0 s→5 t→7 b→8 g→9 l→1",
        ["strip-marks"] = "Strips all combining marks added by this plugin, restoring the plain text",

        // ===== 中文 =====
        ["martian"] = "Per-character substitution using a Simplified-Chinese-to-Mars dictionary (cnchar, MIT)",

        // ===== 编码 =====
        ["base64"] = "UTF-8 bytes → Base64",
        ["rot13"] = "Shifts letters by 13 (applying twice restores the original)",
        ["morse"] = "Letters/digits → Morse code, words separated by /",

        // ===== 扩充：组合符预设 =====
        ["paren-marks"] = "Appends U+035C (combining double breve below) + U+0361 (combining double inverted breve) after each grapheme, drawing arcs that bracket each character",
        ["stripes"] = "Appends U+035E (combining double macron) + U+035F (combining double macron below) after each grapheme, sandwiching the letter between stripes",
        ["lightning"] = "Appends U+035B (combining zigzag above) after each grapheme (coolsymbol \"Lightning/Zigzag\" preset)",
        ["wave-head"] = "Appends U+031A (combining left angle above) after each grapheme",
        ["x-above"] = "Appends U+033D (combining x above) after each grapheme",
        ["dot-below"] = "Appends U+0323 (combining dot below) after each grapheme",
        ["manipuri-underline"] = "Appends U+AADF (Tai Viet symbol koi koi) after each grapheme; renders like an underline",
        ["lace"] = "Appends U+0B8A (Tamil letter UU ஊ) after each grapheme",
        ["grass"] = "Appends U+0DF4 (Sinhala punctuation kunddaliya ෴) after each grapheme",
        ["smoke-arabic"] = "Appends U+06E3 (Arabic small low seen) × 7, stacked like smoke",

        // ===== 扩充：装饰模板 =====
        ["wing-elegant"] = "Javanese brackets ꧁꧂ + floral heart ❦ (U+2766) + Tibetan ornamental brackets ༺༻",
        ["wing-diamond"] = "White diamond ◇ (U+25C7) accent, a \"domineering\" wing variant",
        ["wing-double"] = "Tibetan mark rgya gram shad ༒ (U+0F12) accent",
        ["wing-shimmer"] = "Black four-pointed star ✦ (U+2726) accent",
        ["wing-soft"] = "Eight-petalled outlined black florette ❁ (U+2741) accent",
        ["wing-sanskrit"] = "Tibetan symbol phur pa ࿈ (U+0FC8), mystic-symbol family",
        ["wing-tibetan-ornament"] = "Tibetan pattern built from letter ཌ (U+0F4C), mark ༈ (U+0F08) and letter ད (U+0F51)",
        ["wing-charm"] = "Tibetan initial yig mgo ༄ (U+0F04) + bka- shog yig mgo ༊ (U+0F0A); the suffix is a vowel/tone/ornament string (U+0F7C/82/7E/FC6/FD0)",
        ["wing-heart"] = "Sinhala letter fayanna ෆ (U+0DC6), shaped like sweetheart brackets",
        ["wing-bunny"] = "Subscript parentheses ₍ (U+208D) / ₎ (U+208E) + Canadian syllabics ᐢ (U+1422), kaomoji-style cute template",
        ["wing-moonlight"] = "Last quarter moon ☾ (U+263E) / first quarter moon ☽ (U+263D) + Tibetan ornamental brackets ༺༻",
        ["wing-starmoon"] = "Crescent moons U+263E/U+263D + black four-pointed star ✦ (U+2726)",
        ["wing-asterism"] = "Asterism ⁂ (U+2042), triple asterisk",
        ["wing-retro"] = "Retro pattern of Tibetan brackets ༼ (U+0F3C) / ༽ (U+0F3D) / ༾ (U+0F3E) / ༿ (U+0F3F) and letters ཊ (U+0F4A) / ཏ (U+0F4F)",
        ["wing-dots"] = "Halfwidth ideographic full stop ｡ (U+FF61) + white circle ○ (U+25CB), a Japanese-style border",
        ["wing-nested"] = "Tibetan brackets ༼ (U+0F3C) / ༽ (U+0F3D) nested inside Tibetan ornamental brackets ༺༻",
        ["wing-triangle"] = "White up-pointing triangle △ (U+25B3) accent",
        ["wing-love"] = "Love border built from • (U+2022), ° (U+00B0) and ❤ (U+2764)",

        // ===== 扩充：数字变体 / 俄化 / 火星文还原 =====
        ["digits-circled-sans"] = "1–9 → ➀–➈ (dingbat circled sans-serif digits U+2780–2788; the run covers 1–10 with no zero — 0 and other characters fall back unchanged)",
        ["digits-double-circled"] = "1–9 → ⓵–⓽ (double circled digits U+24F5–24FD; the run covers 1–10 with no zero — 0 and other characters fall back unchanged)",
        ["cyrillic-lookalike"] = "Lookalike Cyrillic uppercase substitution: A→А B→В E→Е K→К M→М H→Н O→О P→Р C→С T→Т X→Х Y→У (U+0410 block)",
        ["martian-reverse"] = "Reversed MartianDictionary map (Mars → Simplified Chinese; first entry wins on one-to-many, non-BMP glyphs skipped)",

        // ===== 中文扩充：简繁 / 拼音 =====
        ["simplified-to-traditional"] = "OpenCC dictionary with greedy longest-phrase matching (头发→頭髮, 皇后→皇后); unmapped characters pass through unchanged",
        ["traditional-to-simplified"] = "OpenCC dictionary with greedy longest-phrase matching (電腦→电脑); unmapped characters pass through unchanged",
        ["pinyin"] = "Hanzi → toned pinyin (mozillazg/pinyin-data, ~24k basic-plane characters), syllables separated by spaces; polyphonic characters use the most common reading, non-Hanzi kept as-is",
        ["pinyin-abbr"] = "Hanzi → pinyin initials (你好吗 → nhm); Latin letters and digits kept as-is",

        // ===== 扩充：编码 / 变换 =====
        ["braille"] = "Grade-1 letter-by-letter: a–z mapped to 8-dot braille cells (a = ⠁ from U+2801), same glyph for both cases; digits prefixed with number sign ⠼ (U+283C), 1–9/0 reuse the a–j shapes",
        ["nato"] = "Letters → ICAO/NATO phonetic words (Alfa Bravo … Zulu); case-insensitive, non-letters ignored",
        ["a1z26"] = "a=1 … z=26: letters joined by hyphens, words separated by spaces (letter-number cipher)",
        ["binary"] = "UTF-8 bytes → 8 binary digits per byte, space-separated (an ASCII character is 8 bits)",
        ["hex"] = "UTF-8 bytes → 2 uppercase hex digits per byte, space-separated (an ASCII character is 2 digits)",
        ["uppercase"] = "Converts every letter to uppercase (invariant culture)",
        ["lowercase"] = "Converts every letter to lowercase (invariant culture)",
        ["alternating-case"] = "Alternates upper/lower case letter by letter (sPoNgE cAsE); non-letters are skipped without advancing the phase",
    };
}
